version: '3'

services:
  frontend:
    container_name: cv_dev
    build:
      context: .
      dockerfile: Dockerfile_DEV
    ports:
      - '8080:8080'
    volumes:
      - './:/app'
    command: npm run serve