version: '3'

services:
  cv:
    container_name: cv
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/node_modules'
    expose:
      - 80
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=cv.kiesel.tech,www.cv.kiesel.tech
      - LETSENCRYPT_HOST=cv.kiesel.tech,www.cv.kiesel.tech

networks:
  proxy:
    external: true