#!/usr/bin/env python3

from pathlib import Path
import subprocess as sp
import argparse as ap
import sys

PAGE_NAME = 'MY CV'
GLOBAL_CONFIG = Path('/root/web/global-config.yml')


def run_development():
    print(f'RUN DEVELOPMENT SERVER FOR: {PAGE_NAME}')
    sp.run(['npm', 'install'])
    sp.run(['docker-compose', '-f', 'docker-compose.dev.yml', 'up', '--build'])


def run_production():
    print(f'RUN PRODUCTION SERVER FOR: {PAGE_NAME}')
    sp.run(['docker-compose', 'up', '--build', '--detach'])


if __name__ == "__main__":
    parser = ap.ArgumentParser(prog='Run Webpage', description='Script to run development or production server')
    parser.add_argument('-dev', '--development', action='store_true', help='run development server')
    parser.add_argument('-prod', '--production', action='store_true', help='run production server')

    args = parser.parse_args()

    if args.development and args.production:
        print('Select production or development not both.')
    elif args.production:
        try:
            run_production()
        except KeyboardInterrupt:
            print('shutting down production server')
            sys.exit(1)
    elif args.development:
        try:
            run_development()
        except KeyboardInterrupt:
            print('shutting down development server')
            sys.exit(1)
    else:
        print('Select either production or development server. (-prod or -dev)')
